{{- range .Values.services }}
{{- if .enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .service.name }}
  namespace: {{ $.Values.namespace.name | quote }}
  labels:
    {{- include "itinerario.labels" $ | nindent 4 }}
    app: {{ .name }}
    {{- if .service.labels }}
    {{- toYaml .service.labels | nindent 4 }}
    {{- end }}
spec:
  type: {{ .service.type }}
  selector:
    app: {{ .name }}
  ports:
    {{- range .service.ports }}
    - protocol: TCP
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}
---
{{- end }}
{{- end }}
