AIRLINE_NAMES = {
    "02": "Hopscotch Air, Inc",
    "07": "State Unitary Enterprise Orenburg Region, International Airport Orenburg",
    "0A": "Joint Stock Company 'Amber Air' Ltd",
    "0C": "Cobra Aviation (Pty) Ltd",
    "0D": "Darwin Airline SA Lugano",
    "0E": "Skynet Asia Airways",
    "0J": "Premium Jet AG",
    "0K": "Aircompany Kokshetau JSC",
    "0N": "North Star Air Limited",
    "0O": "USA Jet Airlines, Inc.",
    "0P": "Palau Asia Pacific Air Inc",
    "0S": "Royal Airlines Limited d/b/a  Spice Jet",
    "0W": "West Caribbean Costa Rica, S.A.",
    "1A": "Amadeus Marketing, S.A.",
    "1B": "Abacus International Pte. Ltd.",
    "1C": "Hewlett-Packard (Schweiz) GmbH",
    "1D": "Radixx Solutions International, Inc.",
    "1E": "Management Information System - Civil Aviation Administration of China",
    "1F": "INFINI Travel Information, Inc.",
    "1G": "Travelport Global Distribution System B.V.",
    "1H": "Comtech-N, JSC",
    "1I": "Montenegro Airlines",
    "1J": "Axess International Network, Inc.",
    "1K": "Sutra, Inc.",
    "1L": "Open Skies, Inc.",
    "1M": "JSC Transport Automated Information Systems - TAIS",
    "1N": "Via World Network",
    "1P": "Travelport d/b/a WorldSpan",
    "1Q": "Indigo Treks LLC",
    "1R": "JR Technologies Ireland",
    "1S": "Amadeus System One",
    "1T": "Hitit Bilgisayar Hizmetleri A.S.",
    "1U": "ITA Software, Inc.",
    "1V": "Galileo International",
    "1W": "Sabre, Inc.",
    "1X": "Fly Branson Travel d/b/a Branson Air Express",
    "1Y": "Electronic Data Systems Corporation",
    "1Z": "Bird Information Systems Private Limited",
    "2A": "AECA - Aeroservicios Ecuatorianos, C.A.",
    "2B": "OJSC Ak Bars Aero",
    "2C": "CMA CGM Air Cargo S.A.S.",
    "2D": "Eastern Airlines, LLC",
    "2E": "ave.com",
    "2F": "Frontier Flying Service, Inc. Branded as Ravn Connect",
    "2G": "Debonair Airways Ltd.",
    "2H": "Hamsal Air Services Limited",
    "2I": "Star Up, S.A.",
    "2J": "Air Burkina",
    "2K": "Kitty Hawk Airways d/b/a 135 Airways, Inc.",
    "2L": "Helvetic Airways AG",
    "2M": "Moldavian Airlines",
    "2N": "Aviation Transport Company Yuzmashavia",
    "2O": "Air Salone",
    "2P": "Air Philippines Corporation d/b/a Airphil Express",
    "2Q": "Air Cargo Carriers, Inc.",
    "2R": "Sunlight Express Airways t/a Sunlight Air",
    "2S": "Island Express",
    "2T": "Tulpar Air Service",
    "2U": "Sunair Express LLC",
    "2V": "Virgin Nigeria Airways",
    "2W": "world2fly, S.L.U.",
    "2Y": "Air Andaman Corporation Limited",
    "2Z": "TTA - Sociedade de Transporte E Trabalho Aereo, S.a.r.l.",
    "3A": "Kenosha Aero. Inc. d/b/a Alliance Airlines",
    "3B": "Aviones de Oriente, C.A. (AVIOR)",
    "3C": "Air Chathams Limited t/a Air Chathams",
    "3D": "Denim Air",
    "3E": "Multi-Aero, Inc.",
    "3F": "Pacific Airways, Inc.",
    "3G": "Gambia Bird Airlines",
    "3H": "Air Inuit Ltd/Ltee.",
    "3I": "Airlift Service Ltd",
    "3J": "Jubba Airways Limited d/b/a Jubba Airways",
    "3K": "Tatonduk Outfitters Ltd. d/b/a Everts Air Alaska / Everts Air Cargo",
    "3L": "Scenic Airlines, Inc.",
    "3M": "Silver Airways LLC",
    "3N": "Airvantage Incorporated",
    "3O": "Peau Vava'u Limited t/a Peau Vava'u",
    "3P": "Thai Pacific Airlines Business Company Ltd.",
    "3Q": "Royal Air Charters",
    "3R": "Avior Regional, C.A.",
    "3S": "Air Guyane S.P.",
    "3T": "American Trans Air, Inc.",
    "3U": "Sichuan Airlines Co. Ltd.",
    "3V": "Viking Airways",
    "3W": "Woodgate Executive Air Charter UK Ltd. d/b/a Euromanx",
    "3X": "Japan Air Commuter Co. Ltd.",
    "3Y": "Baseops International, Inc.",
    "3Z": "Tatonduk Outfitters Ltd. d/b/a Everts Air",
    "4A": "F.S. Air Service, Inc.",
    "4B": "Olson Air Service, Inc.",
    "4C": "Aires S.A. Aerovias de Integracion Regional S.A.) d/b/a LAN Colombia",
    "4D": "Egypt Air Holding Company d/b/a Air Sinai",
    "4E": "Stabo Air Limited",
    "4F": "Air Nigeria plc",
    "4G": "Shenzhen Airlines",
    "4H": "Trans Pacific Air (Malaysia) SDN. BHD.",
    "4I": "IHY Izmir Havayollari A.S. t/a iZair",
    "4J": "Aircompany Somon Air LLC",
    "4K": "Freedom Airline Express",
    "4L": "Palau National Airlines",
    "4M": "African Star Airways (PTY) Ltd.",
    "4N": "Air North Charter",
    "4O": "Orbest Airlines, S.L.",
    "4P": "Public Charters, Inc. d/b/a REGIONAL Sky",
    "4Q": "25Only Aviation GmbH",
    "4R": "Renfe Viajeros Sociedad Mercantil Estatal SA",
    "4S": "F.A. Conner Airways, Inc.",
    "4T": "TCH of Russian Airlines",
    "4U": "Kazan Airenterprise (Tatarstan Airlines)",
    "4V": "BV Airways d/b/a BVI Airways",
    "4W": "Warbelow's Air Ventures, Inc.",
    "4X": "Atlantic Express Airlines",
    "4Y": "Flight Alaska, Inc., d/b/a Yute Air Alaska, Inc.",
    "4Z": "SA Airlink (Pty) Ltd. d/b/a South African Airlink",
    "5A": "Alpine Aviation, Inc.",
    "5B": "Trans International Express",
    "5C": "Cavei Avir Lemitanim t/a Cargo Air Lines",
    "5D": "Air Company Donbass Airlines",
    "5E": "East Coast Flight Services, Inc.",
    "5F": "Arctic Circle Air Service, Inc.",
    "5G": "Aero Cuahonte, S.A. de C.V.",
    "5H": "Trans Executive Airlines of Hawaii t/a transair Express",
    "5I": "Trans Air Georgia",
    "5J": "Private Jet Expeditions, Inc.",
    "5K": "HiFly Transportes Aereos, S.A.",
    "5L": "Fly Salone Airways Ltd",
    "5M": "Joint Stock Company SIAT (Sibaviatrans)",
    "5N": "Joint Stock Company Nordavia Region Airlines",
    "5O": "ASL Airlines France S.A.",
    "5P": "Panorama Airways Limited Liability Company",
    "5Q": "Los Cipreses S.A. d/b/a BQB Lineas Aéreas",
    "5R": "Rutas Aereas, C.A. d/b/a RUTACA",
    "5S": "Global Aviation Services Group",
    "5T": "Air Specialities, Inc. d/b/a Total Air",
    "5U": "AC Challenge Aero LLC",
    "5V": "Tatonduk Outfitters Ltd. d/b/a Everts Air",
    "5W": "Chartair, Inc. d/b/a Air San Juan",
    "5X": "United Parcel Service Company (UPS)",
    "5Y": "Atlas Air, Inc.",
    "5Z": "Airfreight Express Ltd.",
    "6A": "AVIACSA-Consorcio Aviaxsa, S.A. de C.V.",
    "6B": "Baxter Aviation",
    "6C": "Cape Smythe Air",
    "6D": "Royal Daisy Airlines",
    "6E": "Malmo Aviation AB",
    "6F": "Laker Airways, Inc.",
    "6G": "Las Vegas Airlines",
    "6H": "Israir Airlines and Tourism Ltd.",
    "6I": "Alsie Express",
    "6J": "Jubba Airways (K) Limited",
    "6K": "Songbird Airways, Inc.",
    "6L": "Aklak Air, Inc.",
    "6M": "Majestic Air P/L",
    "6N": "Nordic NR Regional AB",
    "6O": "Orbest Airlines, S.L.",
    "6P": "Pacific East Air, Inc.",
    "6Q": "Sham Wings Airlines",
    "6R": "Alrosa Company Limited Mirny Air",
    "6S": "El Sol de America, C.A.",
    "6T": "Air Mandalay Limited",
    "6U": "Air Ukraine",
    "6V": "AVI Inc. d/b/a Air Vegas Inc.",
    "6W": "Libo Air Cargo",
    "6Y": "Nicaraguenses de Aviacion S.A. (NICA)",
    "6Z": "Ronson Aviation d/b/a Cargolift International Airlines",
    "7A": "Haines Airways, Inc.",
    "7B": "Limited Liability Company  Bees Airline",
    "7C": "Columbia Pacific Airlines",
    "7D": "Utility Enterprise DonbassAero Airline",
    "7E": "Nepal Airways Pvt. Ltd.",
    "7F": "Bradley Air Services Limited t/a First Air",
    "7G": "MK Airlines Limited",
    "7H": "Corvus Airlines, Inc. d/b/a Ravn Alaska",
    "7I": "Coastal Travels Limited",
    "7J": "State Air Company Tajikistan d/b/a Tajik Air",
    "7K": "Kogalymavia Airlines JSC",
    "7L": "Air Bristol Ltd.",
    "7M": "Atlantic Air Transport Ltd",
    "7N": "Inland Aviation Services, Inc.",
    "7O": "Galaxy Air",
    "7P": "APA International Air",
    "7Q": "Elite Airways LLC",
    "7R": "Redwing Airways, Inc.",
    "7S": "C Airjet Airlines",
    "7T": "Aero Express Del Ecuador Trans AM",
    "7U": "Alpha Air Transport d/b/a Commercial Aviation Services",
    "7V": "Austin Express, Inc.",
    "7W": "Wind Rose Aviation Company Ltd t/a WINDROSE Airlines",
    "7Y": "Mann Yadanarpon Airlines Co. Ltd.",
    "7Z": "Laker Airways (Bahamas) Limited.",
    "8A": "Arrow Panama, S.A.",
    "8B": "Business Air Centre Co. Ltd. t/a Business Air",
    "8C": "Air Transport International LLC",
    "8D": "Expo Aviation (Pvt.) Limited",
    "8E": "Bering Air, Inc.",
    "8F": "STP Airways",
    "8G": "Mid Africa Aviation",
    "8H": "Highland Airways Limited",
    "8I": "Lipican Aer d.o.o.",
    "8J": "Societe D'Investissement",
    "8K": "K-Mile Air Co. Ltd.",
    "8L": "Cargo Plus Aviation, Inc.",
    "8M": "Mahalo Air, Inc.",
    "8N": "Flagship Airlines, Inc.",
    "8O": "West Coast Air",
    "8P": "Pacific Coastal Airlines Limited",
    "8Q": "Princess Air Plc",
    "8R": "Regourd Aviation d/b/a Amelia",
    "8S": "Salair, Inc.",
    "8U": "Afriqiyah Airways",
    "8V": "Wright Air Service, Inc.",
    "8W": "Burlington Air Express",
    "8X": "SiFly Compagnia Aerea",
    "8Y": "Astro Air International Inc.",
    "8Z": "Congo Airways SA (CGA)",
    "9A": "Aladia Airlines, S.A. de C.V.",
    "9C": "Gill Aviation Ltd.",
    "9D": "Perm Airlines",
    "9E": "Pinnacle Airlines, Inc. d/b/a Northwest Airlink",
    "9F": "Eurostar International Limited",
    "9G": "Galaxy Airways",
    "9H": "Dutch Eagle Express N.V.",
    "9I": "Helitrans AS",
    "9J": "Pacific Island Aviation, Inc.",
    "9K": "Cape Air",
    "9L": "Colgan Air",
    "9M": "Central Mountain Air Ltd.",
    "9N": "Trans State Airlines, Inc. d/b/a Trans World Express",
    "9O": "Transportes Aereos Inter S.A.",
    "9P": "Palau National Airlines",
    "9Q": "Caicos Express Airways",
    "9R": "Rosenbalm Aviation, Inc",
    "9S": "Slovak Airlines",
    "9T": "Travelspan GT Inc",
    "9U": "Air Moldova",
    "9V": "Aviones de Oriente, C.A. (AVIOR)",
    "9W": "Eastwind Airlines, Inc.",
    "9X": "Executive Express Aviation LLC d/b/a Southern Airways",
    "9Y": "Air Kazakstan",
    "A0": "BA EuroFlyer Limited d/b/a British Airways",
    "A1": "G2 Switch Works",
    "A2": "Anima Wings Aviation S.A.",
    "A3": "Aegean Aviation, S.A.",
    "A4": "JSC Azimuth Airlines",
    "A5": "Hop!-Airlinair",
    "A6": "Yunnan Hong Tu Airlines Co., Ltd.",
    "A7": "Air Comet, S.A.",
    "A8": "Ameriflight, LLC",
    "A9": "Airzena Georgian Airlines",
    "AA": "American Airlines",
    "AB": "Air Cortez International",
    "AC": "Air Canada",
    "AD": "Exec. Express II, Inc. d/b/a Aspen Mountain Air / Lone Star Airlines",
    "AE": "Air Europe",
    "AF": "Air France",
    "AG": "Affretair (Private) Limited",
    "AH": "Air Algerie",
    "AI": "Air India Limited",
    "AJ": "Aztec Worldwide Airlines, Inc.",
    "AK": "Altair Airlines, Inc.",
    "AL": "Allegheny Commuter Airlines, Inc. d/b/a USAir Express",
    "AM": "Aeronaves de Mexico, S.A.",
    "AN": "Advanced Air, LLC",
    "AO": "Aviacion Y Comercial S.A. (Aviaco)",
    "AP": "Flugdienst Pegasus",
    "AQ": "Aloha Airlines, Inc.",
    "AR": "Aerolineas Argentinas",
    "AS": "Alaska Airlines, Inc.",
    "AT": "Royal Air Maroc",
    "AU": "Canada Jetlines Operations Ltd",
    "AV": "Avianca - Aerovias Nacionales de Colombia, S.A.",
    "AW": "Empresa Venezolana, Linea Aerea Bolivariana",
    "AX": "Trans State Airlines, Inc. d/b/a Trans World Express",
    "AY": "Finnair Oyj",
    "AZ": "Alitalia - Linee Aeree Italiane",
    "B0": "DreamJet SAS d/b/a La Compagnie",
    "B1": "Bravo Passenger Solution Pte., Ltd.",
    "B2": "Belavia",
    "B3": "Ambassador Airways",
    "B4": "Globespan Airways Limited t/a Flyglobespan",
    "B5": "BBN Hava Yollari ve Tasimacili A.S.",
    "B7": "UNI Airways Corporation",
    "B8": "Italair S.p.A.",
    "B9": "Iran Air Tours Co.",
    "BA": "British Overseas Airways Corporation (BOAC)",
    "BB": "Blackhawk Airways, Inc.",
    "BC": "Brymon Aviation Ltd. d/b/a Brymon Airways",
    "BD": "British Midland Airways Ltd.",
    "BE": "Aero 8 Venezuela",
    "BF": "Markair, Inc.",
    "BG": "Guyana Airways Corp.",
    "BH": "Bismillah Airlines Ltd.",
    "BI": "Bharat Commerce and Industries Ltd.",
    "BJ": "British Caribbean Airways",
    "BK": "Potomac Air, Inc.",
    "BL": "Pacific Airlines Co. Ltd.",
    "BM": "British Midland Regional Ltd. d/b/a flybmi",
    "BN": "Landair International Airlines, Inc.",
    "BO": "AirBridge Cargo Airlines Limited",
    "BP": "Air Botswana Corporation",
    "BQ": "Open Joint-stock company Bukovyna",
    "BR": "Caledonian - British United Airways Ltd.",
    "BS": "Busy Bee Of Norway A/S",
    "BT": "Rolls Royce Ltd. (Bristol Engine Division)",
    "BU": "SAS Braathens AS",
    "BV": "Bavaria Flug-Gesellschaft",
    "BW": "BWIA West Indies Airways Limited",
    "BX": "Compania 'SPANTAX' (Servicios Y Transportes Aereos Air Charter)",
    "BY": "TUI Airways Limited",
    "BZ": "Capital Airlines Ltd.",
    "C0": "One Caribbean Ltd.",
    "C1": "Techtimes Sudamericana S.A.",
    "C2": "Air Caribbean Limited",
    "C3": "Independent Carrier (ICAR)",
    "C4": "Conquest Air, Inc. d/b/a Conquest Air Cargo",
    "C5": "Champlain Enterprises, LLC. t/a CommutAir",
    "C6": "My Freighter Airlines",
    "C7": "Closed Joint Stock Company Samarkand Airways",
    "C8": "Chicago Express Airlines, Inc.",
    "C9": "Cabolar (Pty) Ltd t/a Skywise",
    "CA": "Caledonian Airways Ltd.",
    "CB": "Caribbean-Atlantic Airlines, Inc.",
    "CC": "Air Atlanta Icelandic",
    "CD": "Air Commuter",
    "CE": "Continental Air Services, Inc.",
    "CF": "City Airline AB",
    "CH": "Chicago Helicopter Airways, Inc.",
    "CI": "China Airlines",
    "CJ": "Caribbean Air Transport Co. Inc.",
    "CK": "Aircapitol",
    "CL": "Capitol Airlines, Inc.",
    "CM": "COPA - Airlines",
    "CN": "Westward Airways, Inc.",
    "CO": "Continental Airlines, Inc.",
    "CP": "Compass Airlines LLC",
    "CQ": "Coastal Travels Limited",
    "CR": "OAG Worldwide",
    "CS": "Cambrian Airways Ltd.",
    "CT": "Air One Cityliner S.p.A.",
    "CU": "Empresa Consolidada Cubana de Aviacion",
    "CV": "Cargolux Airlines International, S.A.",
    "CW": "SkyWest Charter LLC",
    "CX": "Cathay Pacific Airways Ltd.",
    "CY": "Cyprus Airways Ltd.",
    "CZ": "Cambata Aviation Ltd.",
    "D0": "DHL Air Limited",
    "D1": "AIR4 Passenger Service Systems, LLC",
    "D2": "Severstal Joint Stock Company",
    "D3": "Daallo Airlines",
    "D4": "Dart Limited Trust Distribution",
    "D5": "NEPC Airlines ( A Division of NEPC Micon Limited)",
    "D6": "Inter-Aviation Services d/b/a Interair South Africa",
    "D7": "Fly Asian Express Sdn Bhd",
    "D8": "Norwegian Air Sweden AOC AB",
    "D9": "Daallo Airlines (Somalia)",
    "DA": "Dan-Air Services Ltd.",
    "DB": "Maleth-Aero AOC Ltd",
    "DC": "Golden Air Flyg AB",
    "DD": "Atlantic Coast Jet, Inc.",
    "DE": "Condor Flugdienst GmbH",
    "DF": "New ACS Ltd.",
    "DG": "Air Atlantique (General Aviation Services Ltd.)",
    "DH": "Atlantic Coast Airlines, Inc. d/b/a United Express",
    "DI": "Norwegian Air UK Ltd.",
    "DJ": "Nordic European Airlines",
    "DK": "Air Corse",
    "DL": "Delta Air Lines, Inc.",
    "DM": "Anda Air LLC",
    "DN": "Piper Aztec Inc, d/b/a Aztec Airways",
    "DO": "Discovery Airways Limited t/a DiscoveryAir",
    "DP": "First Choice Airways Limited",
    "DQ": "Coastal Air Transport, Inc.",
    "DR": "Panair Luftverkehrsgesellschaft mbH & Co.",
    "DS": "Easyjet Switzerland S.A.",
    "DT": "TAAG - Linhas Aereas de Angola S.A.R.L. (TMA)",
    "DU": "Air Commerz Fluggesellschaft mbH",
    "DV": "Germanair Bedarfsluftfahrtgesellschaft mhB",
    "DW": "Joint Stock Company 'Air Company Aero-Charter'",
    "DX": "Danair A/S",
    "DY": "Alyemda - Democratic Yemen Airlines",
    "DZ": "TF - Transportflug GmbH & Co.",
    "E1": "Lydia Yazilim ve Bilgi Teknolojileri sanayi Ve Ticaret Anonim Sirketi",
    "E2": "Eagle Atlantic Airlines Limited",
    "E3": "NewGen Airways Compnay Limited t/a NewGen Airways",
    "E4": "Estelar Latinoamerica C.A.",
    "E5": "Samara Airlines",
    "E6": "AviaExpressCruise Airlines",
    "E7": "Downeast Flying Services, Inc. d/b/a Downeast Express",
    "E8": "City Airways Company Limited dba City Airways",
    "E9": "Evelop Airlines S.L.",
    "EA": "Eastern Air Lines Group, Inc.",
    "EB": "Emery Worldwide Airlines, Inc.",
    "EC": "Avialeasing Aviation Company",
    "ED": "CC AIR, Inc.",
    "EE": "Eastern Air Lines Group, Inc.",
    "EF": "Far Eastern Air Transport Corp.",
    "EG": "Eagle Flying Services Ltd.",
    "EH": "Ehrenström Flyg AB",
    "EI": "Aer Lingus Teoranta",
    "EJ": "New England Airlines",
    "EK": "Emirates",
    "EL": "Nortjet",
    "EM": "Empire Airlines",
    "EN": "Sacchi Air Ferry Enterprises",
    "EO": "Express One International, Inc.",
    "EP": "Aerolineas Peruanas, S.A.",
    "EQ": "Trans European Airways (UK) Ltd. d/b/a TEA (UK) Ltd.",
    "ER": "DHL Airways, Inc.",
    "ES": "Estelar Latinoamerica C.A. d/b/a Estelar",
    "ET": "Ethiopian Airlines Enterprise",
    "EU": "Ecuatoriana de Aviacion, S.A.",
    "EV": "ExpressJet Airlines, LLC",
    "EW": "Eurowings AG",
    "EX": "Executive Airlines and Charter Services, Inc.",
    "EY": "Etihad Airways",
    "EZ": "Evergreen International Airlines, Inc.",
    "F0": "Futura Gael",
    "F1": "Farelogix Inc",
    "F2": "Southern Independent Air Company (UNA)",
    "F3": "Skyways Enterprise AB",
    "F4": "Air Charter, Inc. d/b/a Air Flamenco",
    "F5": "Aerotranscargo SRL",
    "F6": "FlyCompass Service S.r.l.",
    "F7": "Flybaboo SA Geneve",
    "F8": "Freedom Airlines, Inc.",
    "F9": "Frontier Airlines, Inc.",
    "FA": "Air American, Inc.",
    "FB": "Fine Airlines, Inc.",
    "FC": "Fairflight Ltd.",
    "FD": "Ford of Europe Incorporated",
    "FE": "Primaris Airlines, Inc.",
    "FF": "Tower Air, Inc.",
    "FG": "Ariana Afghan Airlines",
    "FH": "Hurkus Havayolu Tasimacilik Ve Ticaret S.A. - Freebird Airlines",
    "FI": "Icelandair",
    "FJ": "Air Pacific Ltd.",
    "FK": "Africa West",
    "FL": "Frontier Airlines",
    "FM": "Flying Syndicate Twente",
    "FN": "fastjet Zimbabwe Limited",
    "FO": "Felix Airways",
    "FP": "TAG Aviation, S.A.",
    "FQ": "Crown Airlines",
    "FR": "Flight Refuelling Ltd.",
    "FS": "Field Aircraft Services Ltd.",
    "FT": "Flying Tiger Line, Inc., The",
    "FU": "Air Littoral",
    "FV": "VIVA, Vuelos Internacionales de Vacaciones, S.A. (VIVA Air)",
    "FW": "Isles of Scilly Skybus Ltd.",
    "FX": "Federal Express Corporation d/b/a FedEx",
    "FY": "Funtshi Aviation Service",
    "FZ": "Dubai Aviation Corporation d/b/a flydubai",
    "G0": "Allanza Glancelot C.A.",
    "G1": "Gorkha Airlines",
    "G2": "Air Foyle Passenger Airlines Limited",
    "G3": "Emerald Airways Limited",
    "G4": "Allegiant Air, Inc.",
    "G5": "Joint Stock Company Enkor",
    "G6": "Aura Airlines S.L. t/a Gowair Vaction Airlines",
    "G7": "GoJet Airlines LLC",
    "G8": "Joint Stock Company Enkor",
    "G9": "Air Arabia PJSC",
    "GA": "Garuda Indonesia Airways P.T.",
    "GB": "Airborne Express, Inc.",
    "GC": "Global Feeder Services, LLC",
    "GD": "Midland Air Cargo Ltd.",
    "GE": "Guernsey Airlines Ltd.",
    "GF": "Gulf Aviation",
    "GG": "Sky Lease I, Inc. t/a Sky Lease Cargo",
    "GH": "Globus LLC",
    "GI": "Air Company Itek-Air Ltd.",
    "GJ": "Challenge Air Cargo, Inc.",
    "GK": "Guy America Airways",
    "GL": "Gronlandsfly Ltd.",
    "GM": "Transwede Airways AB",
    "GN": "Air Gabon",
    "GO": "Go Fly Ltd.",
    "GP": "Air Pegasus GmbH & Co.",
    "GQ": "Big Sky Airlines",
    "GR": "Aurigny Air Services Limited",
    "GS": "Air Foyle Limited",
    "GT": "Gibraltar Airways Ltd.",
    "GU": "AVIATECA, S.A.",
    "GV": "Riga Airlines",
    "GW": "Golden West Airlines, Inc.",
    "GX": "Global International Airways",
    "GY": "Tri-MG Intra Asia Airlines, PT.",
    "GZ": "Gregory Air Services Ltd.",
    "H1": "Hahn Air Systems",
    "H2": "Sky Service S.A.",
    "H3": "Saga Airlines",
    "H4": "Raven Air, LLC d/b/a Island Hoppers Aerial Adventures",
    "H5": "Thomas Cook Airlines Balearics S.L.",
    "H6": "Airline Chelyabinsk Air Enterprise Joint Stock Company",
    "H7": "Air Alfa Havayollan Ve Tie A.S.",
    "H8": "Khabarovsk Aviation Group",
    "H9": "Helitt Lineas Aereas",
    "HA": "Hawaiian Airlines",
    "HB": "Harbor Airlines",
    "HC": "Aviaction, Hanseatische Luftreederei",
    "HD": "New York Helicopters Corp.",
    "HE": "LGW-Luftfahrtgesellschaft Walter GmbH",
    "HF": "TUIfly GmbH",
    "HG": "Florida West Airlines",
    "HH": "Limited Liability Company Qanot Sharq",
    "HI": "Papillon Airways, Inc.",
    "HJ": "Haywards Aviation Ltd.",
    "HK": "Compagnie Generale Aerienne Africaine",
    "HL": "Holiday Express, Deutsche Luftverkehrsges",
    "HM": "Humber Airways Ltd.",
    "HN": "NLM Cityhopper B.V.",
    "HO": "Juneyao Airlines Co. Ltd.",
    "HP": "America West Airlines, Inc.",
    "HQ": "Business Express Airlines, Inc.",
    "HR": "Air Bremen GmbH & Co. Luftverkehrs KG",
    "HS": "Beechcraft Sales (PTY) Ltd.",
    "HT": "Aeromist - Kharkiv Ltd.",
    "HU": "Formosa Airlines Corp.",
    "HV": "Transavia Holland B.V.",
    "HW": "Guernsey Airlines Ltd.",
    "HX": "South West Aviation Company Ltd.",
    "HY": "Uzbekistan Havo Yullary - Uzbekistan Airways",
    "HZ": "Thurston Aviation Ltd.",
    "I2": "Compania Operadora de Corto y Medio Radio Iberia Express, S.A.U",
    "I3": "ATA Airlines",
    "I4": "Scott Air, LLC d/b/a Island Air Express",
    "I5": "Compagnie Aerienne du Mali S.A. (CAM)",
    "I6": "Sky Eyes Co. Ltd.",
    "I7": "PT. Indonesia Air Transport. Tbk",
    "I8": "Izhavia Public Stock Company",
    "I9": "Air Italy S.p.A.",
    "IA": "Iraqi Airways",
    "IB": "Iberia - Lineas Aereas de Espana",
    "IC": "NACIL d/b/a Indian Airlines",
    "ID": "Atlantic Deutsche Luftverkehrs AG",
    "IE": "Solomon Islands Airways Ltd.",
    "IF": "Islas Airways",
    "IG": "Meridiana Fly S.p.A.",
    "IH": "Lynden Air Cargo LLC",
    "II": "Evex Fluggsellschaft mbh & Co KG",
    "IJ": "Spring Airlines Japan Co. Ltd.",
    "IK": "Tradewinds Airways Ltd.",
    "IL": "Istanbul Airlines A.S.",
    "IM": "Invicta International Airlines Ltd.",
    "IN": "Ryan Aviation Corp. d/b/a Ryan International Airlines",
    "IO": "Closed Joint Stock Company IrAero",
    "IP": "Interregional Fluggesellschaft mbH",
    "IQ": "Qazaq Air Joint Stock Company",
    "IR": "Iran National Airlines Corp. (Iran Air)",
    "IS": "Island Airlines, Inc.",
    "IT": "Tiger Airways Taiwan Co. Ltd.",
    "IU": "Interswede Aviation AB",
    "IV": "British Island Airways Ltd. (BIA)",
    "IW": "Ryanair Ltd.",
    "IX": "Internacional de Aviacion (INAIR)",
    "IY": "Yemenia - Yemen Airways",
    "IZ": "Arkia Israel Inland Airlines",
    "J0": "Jet Link Express Ltd.",
    "J1": "Primair, Inc.",
    "J2": "Azerbaijan Hava Yollary",
    "J3": "Northwestern Air Lease Ltd.",
    "J4": "Badr Airlines",
    "J5": "Alaska Seaplane Service, L.L.C.",
    "J6": "Joint-Stock Holding Co. Aviation Commercial - AVCOM",
    "J7": "ValuJet Airlines, Inc.",
    "J8": "Berjaya Air Sdn. Bhd.",
    "J9": "Guinee Airlines, S.A.",
    "JA": "Scimitar Airlines Ltd.",
    "JB": "British Caledonian Airways (Charter) Limited",
    "JC": "Rocky Mountain Airways",
    "JD": "TOA Domestic Airlines",
    "JE": "Sky Charters Ltd.",
    "JF": "L.A.B. Flying Service, Inc.",
    "JG": "Burnthills Aviation Ltd.",
    "JH": "Pan Adria",
    "JI": "Aquair Luftfahrt GmbH & Co.",
    "JJ": "Aviogenex",
    "JK": "Friendly Islands Airways Limited",
    "JL": "Japan Airlines Company Ltd.",
    "JM": "Jambojet Limited",
    "JN": "Rich International Airways, Inc.",
    "JO": "Aeronaves del Oeste, S.A.",
    "JP": "Inex-Adria Airways",
    "JQ": "Air Jamaica Express Limited",
    "JR": "Air Yugoslavia",
    "JS": "Aeronaves del Sur, S.A.",
    "JT": "Jamaica Air Services",
    "JU": "Jugoslovenski Aerotransport (JAT)",
    "JV": "Perimeter Aviation LP d/b/a Bearskin Airlines",
    "JW": "Arrow Air, Inc.",
    "JX": "Jett8 Airlines Cargo Pte Ltd",
    "JY": "Jersey European Airways Limited d/b/a British European",
    "JZ": "Zaire Aero Service (ZAS)",
    "K0": "Sunwing Airlines Inc",
    "K1": "Topas Co. Ltd.",
    "K2": "Paklook Air, Inc. d/b/a Airlift Alaska",
    "K3": "Safe Air Company Limited",
    "K4": "Kalitta Air LLC",
    "K5": "Silverstone Air Services Ltd",
    "K6": "Apollo Airlines, S.A.",
    "K7": "National Aircompany Sakha Avia",
    "K8": "Kannithi Aviation Company Limited d/b/a Kan Air",
    "K9": "Krasavia, State Enterprise of Krasnoyarsk Territory",
    "KA": "Aero Nomad Airlines, LLC",
    "KB": "Burnthills Aviation Ltd.",
    "KC": "Trans Atlantic Airlines",
    "KD": "British Island Airways Ltd. (BIA)",
    "KE": "Korean Air Lines Co. Ltd.",
    "KF": "Congofrigo",
    "KG": "Key Lime Air Corporation",
    "KH": "Aeko Kula, Inc d/b/a Aloha Air Cargo",
    "KI": "KaiserAir, Inc.",
    "KJ": "British Mediterranean Airways Limited",
    "KK": "Transmeridian Air Cargo Ltd.",
    "KL": "KLM Royal Dutch Airlines (Koninklijke Luchtvaart Maatschappij N.V.)",
    "KM": "Air Malta co. Ltd.",
    "KN": "Morris Air Service",
    "KO": "Aerolineas Colonia S.A. (Arco S.A.)",
    "KP": "Kiwi International Air Lines",
    "KQ": "Kenya Airways",
    "KR": "Aviation Company MDA",
    "KS": "Saturn Airways, Inc.",
    "KT": "Mahogany Air Charters",
    "KU": "Kuwait Airways",
    "KV": "Modern Air Transport, Inc.",
    "KW": "Pan American World Airways, Inc.",
    "KX": "Cayman Airways Limited",
    "KY": "Linhas Aereas de Air Sao Tome And Principe",
    "KZ": "Nippon Cargo Airlines",
    "L0": "Reliant Air Charter, Inc.",
    "L1": "Searcharter Limited",
    "L2": "Lynden Air Cargo, LLC",
    "L3": "Lynx Aviation, Inc.",
    "L4": "Linea Turistica Aereotuy Lta, C.A.",
    "L5": "Helikopter Service A/S",
    "L6": "Mauritanian Airlines International",
    "L7": "Laoag International Airlines",
    "L8": "Leisure Air",
    "L9": "Air Mali, S.A.",
    "LA": "Linea Aerea Nacional-Chile S.A. Lan-Chile",
    "LB": "LEPL Projects Limited t/a Air Costa",
    "LC": "Loganair Limited",
    "LD": "Linea Turistica Aereotuy Lta, C.A.",
    "LE": "Lion Air Cargo Tanzania Limited",
    "LF": "Corporate Flight Management",
    "LG": "Luxair",
    "LH": "Lufthansa Cargo AG",
    "LI": "Leeward Islands Air Transport (1974) Ltd. (LIAT)",
    "LJ": "Sierra National Airlines",
    "LK": "Arawak Airlines Ltd.",
    "LL": "Loftleidir, Icelandic Airlines Ltd.",
    "LM": "Loganair Limited",
    "LN": "Jamahirya Libyan Arab Airlines",
    "LO": "Polskie Linie Lotnocze (LOT)",
    "LP": "The Hawaii Express",
    "LQ": "Lebanese Air Transport",
    "LR": "Lineas Aereas Costarricenses S.A. (LACSA)",
    "LS": "Express Air Services (Channel Islands) Ltd.",
    "LT": "Air Lituancia",
    "LU": "LTU Lufttransport Unternehmen Süd GmbH Co",
    "LV": "Aeropostal de Venezuela, C.A.",
    "LW": "Air Nevada Airlines Inc. d/b/a Pacific Wings",
    "LX": "Los Angeles Airways, Inc.",
    "LY": "EL AL Israel Airlines Ltd.",
    "LZ": "Swiss Global Air Lines AG",
    "M0": "Aero Mongolia",
    "M1": "Zambezi Transfer Services CC dba Air Reps",
    "M2": "Mahfooz Aviation G. Limited",
    "M3": "ABSA - Aerolinhas Brasileiras S.A. d/b/a TAM Cargo",
    "M4": "Interimpex - Avioimpex",
    "M6": "Amerijet International, Inc.",
    "M7": "Mountain Air Express, Inc.",
    "M8": "Moscow Airways",
    "M9": "Motor-Sich, JSC",
    "MA": "MALEV Hungarian Airlines Public Limited Company (MALEV p.l.c.)",
    "MB": "Federal Express Corporation (Fedex)",
    "MC": "Air Mobility Command",
    "MD": "FIM Air Ltd.",
    "ME": "Middle East Airlines - AirLiban",
    "MF": "Marshall's Flying Services Ltd.",
    "MG": "MGM Grand Air, Inc.",
    "MH": "Malaysia Airlines Berhad (MAL)",
    "MI": "Mackey International",
    "MJ": "Manchester Airport Agencies",
    "MK": "Air Mauritius",
    "ML": "Midway Airlines",
    "MM": "Peach Aviation Limited",
    "MN": "Commercial Airways (Pty.) Ltd.",
    "MO": "Mohawk Airlines, Inc.",
    "MP": "Martin's Luchtvervoermaatschappij (Martin's Aircharter Company M.A.C.) N.V",
    "MQ": "Simmons Airlines Inc. d/b/a American Eagle",
    "MR": "Hunnu Air - Wings of Mongolia",
    "MS": "United Arab Airlines (UAA)",
    "MT": "Mid Airlines",
    "MU": "Misr Air",
    "MV": "Air Mascareignes Ltd. t/a Air Mascareignes",
    "MW": "Mokulele Flight Service, Inc.",
    "MX": "Breeze Aviation Group, Inc. t/a Breeze Airways",
    "MY": "MAXjet Airways Inc.",
    "MZ": "Amakusa Airlines Co., Ltd.",
    "N0": "Norse Atlantic Airways AS",
    "N1": "Nextres AB",
    "N2": "Jet Charter, Inc.",
    "N3": "Omskavia Airline, Public Joint-Stock Society",
    "N4": "LLC 'Nord Wind'",
    "N5": "Skagway Air Service, Inc.",
    "N6": "Aero Continente",
    "N7": "National Airlines, Inc.",
    "N8": "National Air Cargo Group, Inc. d/b/a National Airlines",
    "N9": "North Coast Aviation Pty Ltd.",
    "NA": "North American Airlines, Inc.",
    "NB": "Skypower Express Airways Nigeria Ltd.",
    "NC": "North Central Airlines, Inc.",
    "ND": "Airlink Limited",
    "NE": "Northeast Airlines, Inc.",
    "NF": "Air Vanuatu (Operations) Limited",
    "NG": "Gill Aviation Ltd.",
    "NH": "All Nippon Airways Co. Ltd.",
    "NI": "Portugalia - Companhia Portuguesa de Transportes Aereos SA",
    "NJ": "Vanguard Airlines, Inc.",
    "NK": "Air Vanuatu",
    "NL": "Aero4M d.o.o. d/b/a Amelia International",
    "NM": "Air Madrid Lineas Aereas, S.A.",
    "NN": "VIM Airlines",
    "NO": "Atlantis - Luftverkehrsunternehmen",
    "NP": "Heavylift Cargo Airlines Ltd.",
    "NQ": "New Zealand Ministry of Transport",
    "NR": "CSE Aviation Ltd.",
    "NS": "Northeast Airlines Ltd.",
    "NT": "Northern Air Taxis Ltd.",
    "NU": "Southwest Airlines",
    "NV": "Northern Executive Aviation Ltd.",
    "NW": "Northwest Orient Airlines, Inc.",
    "NX": "Air Macau Company Limited",
    "NY": "New York Airways, Inc.",
    "NZ": "Air New Zealand Limited",
    "O2": "Hopscotch Air, Inc.",
    "O3": "Oriental Air Bridge Co. Ltd.",
    "O4": "orange2fly Airlines S.A.",
    "O5": "Comores Aviation International",
    "O6": "Oceanair Linhas Aereas Ltda t/a Avianca Brazil",
    "O7": "Omni-blu Aviation Limited",
    "O8": "Siam Air Transport Co., Ltd.",
    "O9": "Nova Airlines",
    "OA": "Olympic Airways",
    "OB": "Oasis International Airlines",
    "OC": "Air California",
    "OD": "Zuliana de Aviacion .C.A.",
    "OE": "Westair Commuter Airlines, Inc. / United Express",
    "OF": "British Aircraft Corp. (BAC) (Filton Division)",
    "OG": "Orientair Ltd.",
    "OH": "SFO Helicopter Airlines, Inc.",
    "OI": "H. Jonsson air Taxi",
    "OJ": "Overland Airways Limited",
    "OK": "Ceskoslovenske Aerolinie (CSA)",
    "OL": "Polynesian Limited",
    "OM": "Monarch Airlines Ltd.",
    "ON": "Nauru Air Corporation t/a Our Airline",
    "OO": "Sky West Airlines",
    "OP": "Flying Boat Inc. d/b/a Chalk's International Airines",
    "OQ": "Zambian Express Airways (19195) Limited",
    "OR": "TUI Airlines Nederlands B.V. t/a Arkefly",
    "OS": "Austrian Airlines",
    "OT": "Servicio de Transportes Aereos de Sao Tome",
    "OU": "Court Line Aviation Ltd.",
    "OV": "Overseas National Airlines, Inc.",
    "OW": "Executive Airlines, Inc.",
    "OX": "Orient Thai Airlines Company Limited",
    "OY": "African Intercontinental Airways",
    "OZ": "Ozark Airlines",
    "P0": "Proflight Commuter Services Limited",
    "P1": "Public Charters, Inc. d/b/a REGIONAL Sky",
    "P2": "Utair Aviation Joint-Stock Company",
    "P3": "Aeroflot - Plus J.S.C.",
    "P4": "Air Peace Limited",
    "P5": "AeroRepública, S.A. t/a Copa Airlines Colombia",
    "P6": "Trans Air",
    "P7": "Supernova Airlines LLC",
    "P8": "Mekong Aviation JSC (Air Mekong)",
    "P9": "Pro Air, Inc.",
    "PA": "Pan American World Airways (Pan-Am)",
    "PB": "Provincial Airlines",
    "PC": "Pegasus Hava Tasimaciligi A.S.",
    "PD": "Pluto Airlines LLC",
    "PE": "People Express Airlines, Inc.",
    "PF": "AirSial Limited",
    "PG": "Aero Spacelines",
    "PH": "Polynesian Airlines Ltd.",
    "PI": "Piedmont Airlines, Inc.",
    "PJ": "Peregrine Air Services Ltd.",
    "PK": "Pakistan International Airlines",
    "PL": "Plymouth Aero Club Ltd.",
    "PM": "Brymon Aviation Ltd. d/b/a Brymon Airways",
    "PN": "Société Nouvelle Air Martinique",
    "PO": "Polar Air Cargo, Inc.",
    "PP": "Private Jet Services AG",
    "PQ": "SkyUp Airlines",
    "PR": "Philippine Air Lines, Inc. (PAL)",
    "PS": "PSA - Pacific Southwest Airlines",
    "PT": "Provincetown-Boston Airlines, Inc.",
    "PU": "Pluna Lineas Aereas Urugauyas, S.A.",
    "PV": "PAN AIR Lineas Aereas, S.A.",
    "PW": "Precision Air Services Ltd.",
    "PX": "Pressed Steel Co. Ltd. (Aviation Division) Oxford",
    "PY": "Surinam Airways Ltd.",
    "PZ": "TAM - Transportes Aereos del Mercosur, S.A.",
    "Q1": "PT. Sqiva Sistem",
    "Q2": "Island Aviation Services Ltd.",
    "Q3": "Zambian Airways",
    "Q4": "Steffen Air Charter Services d/b/a Swazi Express Airways",
    "Q5": "Sutra Air Charter (M) Sdn. Bhd.",
    "Q6": "Aero-Cóndor, S.A.",
    "Q7": "Interstate Equipment Leasing, Inc. d/b/a Swift Air",
    "Q8": "Pacific East Asia Cargo Airlines, Inc.",
    "Q9": "Green Africa Airways Limited",
    "QA": "Queen Bilqis Airways",
    "QB": "Qeshm Air",
    "QC": "Air Zaire",
    "QD": "Air Atlantic",
    "QE": "European Continental Airways (ECA)",
    "QF": "Qantas Empire Airways",
    "QG": "Global Aviation Operations (PTY) Ltd",
    "QH": "Bamboo Airways Joint Company Limited",
    "QI": "Ibom Airlines Limited",
    "QJ": "Jet Airways, Inc.",
    "QK": "Compagnie Aeromaritime d'affretement",
    "QL": "Air Gulf Falcon PTY Ltd.",
    "QM": "Monacair",
    "QN": "Kabo Airlines Limited",
    "QO": "Malmo Aviation AB",
    "QP": "Airkenya Aviation Ltd. d/b/a Regional Air",
    "QQ": "Reno Air, Inc.",
    "QR": "Qatar Airways (W.L.L.)",
    "QS": "African Safari Airways Ltd.",
    "QT": "Inter City Airlines",
    "QU": "Airline Utair - Ukraine",
    "QV": "Lao Aviation",
    "QW": "Mines Air Services Ltd.",
    "QX": "Horizon Airlines, Inc.",
    "QY": "Safari Air Services Ltd.",
    "QZ": "Zambia Airways",
    "R0": "M/S Royal Airlines (PVT) Limited",
    "R1": "Zapways, Inc.",
    "R2": "Groupe Transair S.A.",
    "R3": "JSC Airline Yakutia",
    "R4": "Real Tonga Airline",
    "R5": "Malta Air Charter Company Limited",
    "R6": "Joint Stock Company Airlines 'DOT LT'",
    "R7": "Aeroservicios Carabobo C.A. Aserca",
    "R8": "Sundance Air Venezuela, S.A.",
    "R9": "Suasa Airlines Sdn Bhd",
    "RA": "Nepal Airlines Corporation t/a Royal Nepal Airlines",
    "RB": "Syrian Arab Airlines",
    "RC": "Republic Airlines",
    "RD": "Ryan International Airlines",
    "RE": "Airhub Airlines Limited",
    "RF": "Florida West International Airways, Inc.",
    "RG": "Rotana Jet Aviation d/b/a Rotana Jet",
    "RH": "Air Zimbabwe",
    "RI": "Rutas Internacionales Peruanas, S.A. (RIPSA)",
    "RJ": "Royal Jordanian Airlines Company",
    "RK": "Ryanair UK Limited",
    "RL": "E.S. & A. Robinson (Holdings) Ltd.",
    "RM": "McAlpine Aviation",
    "RN": "Rayani Air Sdn. Bhd.",
    "RO": "TAROM - Romanian Air Transport",
    "RP": "Budapest Aircraft Service Ltd.",
    "RQ": "International Synthetic Rubber Co. Ltd.",
    "RR": "Royal Air Force",
    "RS": "Aerofreight Airlines, JSC",
    "RT": "Rainbow Airlines (Private) Limited",
    "RU": "SATA",
    "RV": "Venezolana",
    "RW": "Hughes Airwset",
    "RX": "British Independent Airways Ltd.",
    "RY": "Arista International Airlines",
    "RZ": "Rich International Airways, Inc.",
    "S0": "Aerolineas Sosa, S.A. de C.V.",
    "S1": "Lufthansa Systems AG",
    "S2": "Sahara India Airlines Ltd.",
    "S3": "Santa Barbara Airlines, C.A.",
    "S4": "SATA International Servicos e Transportes Aereos, S.A.",
    "S5": "Shuttle America Corporation",
    "S6": "Mountain Bird, Inc. d/b/a Salmon Air",
    "S7": "Siberia Airlines - Sibir Airlines",
    "S8": "Shovkoviy Shlyah Ltd. Airlines",
    "S9": "SK Air a.s.",
    "SA": "South African Airways SOC Limited",
    "SB": "Seaboard World Airlines, Inc.",
    "SC": "Shandong Airlines",
    "SD": "Sudan Airways Co. Ltd.",
    "SE": "Wings of Alaska",
    "SF": "Societe Air Charter SAFA",
    "SG": "Spacegrand",
    "SH": "FlyMe Sweden AB",
    "SI": "SaBer Air Private Limited",
    "SJ": "Southern Air Transport, Inc.",
    "SK": "Snowflake",
    "SL": "Southeast Airlines, Inc.",
    "SM": "Sunworld International Airlines, Inc.",
    "SN": "Delta Air Transport N.V. d/b/a SN Brussels Airlines",
    "SO": "Superior Aviation, Inc.",
    "SP": "Sociedade Acoriana de Tranportes Aereos, Lda. (SATA)",
    "SQ": "Singapore Airlines Cargo PTE Ltd.",
    "SR": "Swiss Air Transport Co. Ltd. (Swissair)",
    "SS": "Sagitair Limited",
    "ST": "SAT  -  Special Air Transport Fluggesellschaft mbH",
    "SU": "Aeroflot Russian Airlines",
    "SV": "Saudi Arabian Airlines Corporation",
    "SW": "Swiss Airtainer SA",
    "SX": "Skybus Airlines",
    "SY": "MN Airlines, LLC d/b/a Sun Country Airlines",
    "SZ": "Air Southwest Ltd.",
    "T0": "Trans American Airlines, S.A. TACA Peru",
    "T1": "Sysops, Inc.",
    "T2": "Thai Air Cargo Co., Ltd.",
    "T3": "Transafricaine Air Cargo",
    "T4": "Transeast Airlines Ltd.",
    "T5": "Akhal - Turkmenistan Airlines",
    "T6": "Tavrey Aircompany",
    "T7": "TransGlobal Airways Corporation",
    "T8": "TUM AeroCarga de Mexico, S.A. de C.V.",
    "T9": "Turpial Airlines, C.A.",
    "TA": "TACA International Airlines, S.A.",
    "TB": "Shuttle Inc. d/b/a USAir Shuttle",
    "TC": "Air Tanzania Corporation",
    "TD": "Transporte Aéreo de Carga, S.A.",
    "TE": "SkyTaxi sp. z.o.o.",
    "TED": "Teddy Air A/S",
    "TF": "Thai Flying Service Co. Ltd.",
    "TG": "Thai Airways International Public Company Ltd.",
    "TH": "Thai Airways Co. Ltd.",
    "TI": "Tropic Ocean Airways, LLC.",
    "TJ": "Jet Charter Service, Inc. t/a Jet 24",
    "TK": "Turk Hava Yollari (Turkish Airlines)",
    "TL": "Trans Mediterranean Airways (TMA)",
    "TM": "LAM - Linhas Aereas de Mocambique",
    "TN": "Air Tahiti Nui",
    "TO": "Transavia France S.A.S.",
    "TP": "Transportes Aereos Portugueses, E.P.",
    "TQ": "Tailwind Air, LLC",
    "TR": "Compania de Aviacion Trans-Europa",
    "TS": "Aloha Airlines, Inc.",
    "TT": "Texas International Airways, Inc.",
    "TU": "Tunisair",
    "TV": "Trans International Airlines, Inc.",
    "TW": "Trans World Airlines, Inc.",
    "TX": "Transportes Aéreos Nacionales, S.A. - TAN Honduras",
    "TY": "Air Caledonie",
    "TZ": "ATA Airlines, Inc. d/b/a ATA",
    "U0": "Ultra Air S.A.S.",
    "U1": "Videcom International Limited",
    "U2": "UFS, Inc.",
    "U3": "Air Company 'Sky Gates Airlines' LLC",
    "U4": "Burjat Airlines",
    "U5": "International Business Air",
    "U6": "Ural Airlines",
    "U7": "USA Jet Airlines, Inc.",
    "U8": "Tus Airways Ltd.",
    "U9": "Tatarstan State Enterprise Aircompany",
    "UA": "United Air Lines, Inc.",
    "UB": "Air Cargo Global s.r.o.",
    "UC": "Linea Aerea del Cobre Ltda. (LADECO)",
    "UD": "UR Airlines d/b/a UBD",
    "UE": "Air Euroamerica S.A. (Uair)",
    "UF": "Universal Flying Services Ltd.",
    "UG": "Empresa (Aero Uruguay), S.A.",
    "UH": "Jet Exchange Limited",
    "UI": "Ultimate Jetcharters, Inc.",
    "UJ": "State Airline Ukraine National Airlines",
    "UK": "KLM uk Ltd.",
    "UL": "Air Lanka Limited",
    "UM": "Air Zimbabwe Corporation",
    "UN": "Universair, SA",
    "UO": "Empreas Aero Uruguay, S.A.",
    "UP": "Air Foyle Limited",
    "UQ": "Ryanair Eurpoe",
    "UR": "Aerosun International, Inc.",
    "US": "Silk Avia LLC",
    "UT": "Utair Aviation Joint-Stock Company",
    "UU": "Air Reunion",
    "UV": "Universal Airways, Inc.",
    "UW": "Air Rwanda",
    "UX": "Air Europa Lineas Aereas, S.A.",
    "UY": "Sky Prime Aviation Services",
    "UZ": "United Steel Companies Ltd. Air Transport",
    "V0": "Conviasa",
    "V1": "Travelport, Inc",
    "V2": "Avialeasing Aviation Company",
    "V3": "Veg Air S.R.L.",
    "V4": "Vensecar Internacional, C.A.",
    "V5": "VIP Wings, Ltd",
    "V6": "Clairmont Holdings Ltd dba VI Air Link",
    "V7": "Alaeo S.L. t/a Volotea Airlines",
    "V8": "ATRAN-Aviatrans Cargo Airlines",
    "V9": "Star1 Airlines",
    "VA": "VIASA - Venezolana Internacional de Aviacion SA",
    "VB": "Pacific Express",
    "VC": "Servicios Avensa S.A. (SERVIVENSA)",
    "VD": "RTZ Services Limited",
    "VE": "Aerovias Venezolanas, S.A. (AVENSA)",
    "VF": "British World Airlines",
    "VG": "Air Siam Air Company Limited",
    "VH": "Aeropostal Alas de Venezuela, C.A.",
    "VI": "VIVA, Vuelos Internacionales de Vacaciones, S.A. (VIVA Air)",
    "VJ": "Vietjet Aviation Joint Stock Company",
    "VK": "Virgin Nigeria Airways",
    "VL": "Eagle Air Ltd. (Arnarflug H/F)",
    "VM": "Abacus Air",
    "VN": "Hang Khong Veitnam",
    "VO": "VLM Airlines d.d.",
    "VP": "Villa Air Private Limited t/a flyme",
    "VQ": "Vintage Props and Jets, Inc.",
    "VR": "Transportes Aereos de Cabo Verde (TACV)",
    "VS": "Tradewinds Airways Ltd.",
    "VT": "Air Polynesie",
    "VU": "Vietnam Travel Airlines Joint stock company d/b/a Vietravel Airlines",
    "VV": "AeroSvit Airlines private stock company",
    "VW": "Virgin Air, Inc.",
    "VX": "Vietnam Air Transport (VIAT)",
    "VY": "Highland Express",
    "VZ": "MyTravel Lite",
    "W1": "World Ticket Ltd",
    "W2": "World Airlines Limited",
    "W3": "Arik Air",
    "W4": "Wizz Air Malta Limited",
    "W5": "Mahan Airlines",
    "W6": "West Isle Air, Inc.",
    "W7": "Western Pacific Airlines, Inc.",
    "W8": "Winnport Logistics Ltd.",
    "W9": "Eastwind Airlines, Inc.",
    "WA": "Western Airlines, Inc.",
    "WB": "Rwandair Express",
    "WC": "Wien Consolidated Airlines Ltd.",
    "WD": "DAS Air Limited",
    "WE": "Challenge Air Cargo, Inc.",
    "WF": "Wideroe's Flyveselskap A/S",
    "WG": "Fairflight Charters",
    "WH": "La Nueva Aerolinea, S.A. t/a wingo",
    "WI": "White Airways S.A.",
    "WJ": "Nihon Kinkyori Airways",
    "WK": "Western Alaska Airlines, Inc.",
    "WL": "Caribbean Sun Airlines, Inc. d/b/a World Atlantic Airlines",
    "WM": "Windward Islands Airways International N.V.",
    "WN": "Southwest Airlines Co.",
    "WO": "World Airways, Inc.",
    "WP": "Hawaii Island Air. Inc d/b/a Island Air",
    "WQ": "Interstate Equipment Leasing, Inc. d/b/a Swift Air",
    "WR": "Royal Tongan Airlines",
    "WS": "Wiltshire School of Flying LTd.",
    "WT": "Swiftair, S.A.",
    "WU": "Wizz Air Ukraine, LLC",
    "WV": "Air South, Inc.",
    "WW": "Scottish European Airways Ltd.",
    "WX": "Air Zimbabwe Corporation",
    "WY": "Oman Aviation Services Co. (SAOG)",
    "WZ": "Berlin European U.K. Ltd.",
    "X1": "FORTHcrs SA",
    "X3": "Baikal Airlines",
    "X4": "Vanair Limited",
    "X5": "Sunworld International Airlines, Inc.",
    "X6": "Challenge Air Cargo Limited",
    "X7": "Zambia Skyways Ltd.",
    "X8": "Airmax S.A.",
    "X9": "Khors Aircompany Ltd.",
    "XA": "ARINC (Aeronautical Radio, Inc.)",
    "XB": "International Air Transport Association",
    "XC": "Air Routing International Corp.",
    "XD": "Universal Air Travel Plan (UATP)",
    "XE": "South Central Air, Inc.",
    "XF": "Spacegrand Aviation Services - SGA Ltd.",
    "XG": "North American Airlines, Inc.",
    "XH": "Special Ground Handling Service - XH",
    "XI": "International Aeradio Ltd.",
    "XJ": "Mesaba Aviation, Inc.",
    "XK": "Air Hawaii",
    "XL": "Aerolane - Lineas Aereas Nacionales del Ecuador S.A. (Lan Ecuador)",
    "XM": "Zimex Aviation Limited",
    "XN": "Fly Logic Malmo AB",
    "XO": "LTE International Airways S.A.",
    "XP": "T.E.M. Enterprises Inc. d/b/a  Xtra Airways",
    "XR": "Touristic Aviation Services Ltd. t/a Corendon Airlines Europe",
    "XS": "SITA - Airlines Worldwide Telecommunications and Information Services",
    "XT": "Skystar Airways Company Limited",
    "XU": "Aerorepresentaciones Tupac Amaru",
    "XV": "Waltair I Linkoping AB",
    "XW": "Pete Air Co., Ltd.",
    "XY": "Flynas Company Closed Joint Stock owned by (NAS Holding) JSC",
    "XZ": "South African Express Airways (Pty) Ltd.",
    "Y0": "Friendship Airways d/b/a Yellow Air Taxi",
    "Y1": "Travel Technologyu Interactive SA",
    "Y2": "Globespan Airways Limited t/a Flyglobespan",
    "Y3": "Syphax Airlines S A",
    "Y4": "Eagle Aviation Ltd.",
    "Y5": "Pace Airlines, Inc",
    "Y6": "Europe Elite",
    "Y7": "Flyjet Limited t/a Silver",
    "Y8": "Yangtze River Express Airlines Co., Ltd.",
    "Y9": "Kish Air",
    "YA": "Yeti Airlines (P) Ltd.",
    "YB": "Bora Jet Havacilik Tasimacilik Ucak",
    "YC": "Trygg-Flyg Erik Trygg AB",
    "YD": "Synergy Aviation Ltd.",
    "YE": "Yan Air Ltd.",
    "YG": "South Airlines",
    "YH": "Sunsplash Aviation, LLC.",
    "YI": "Air Sunshine, Inc.",
    "YJ": "NAC Aviation Business Centre (PTY) Ltd. d/b/a National Airlines",
    "YK": "Kibris Turk Hava Yollari",
    "YL": "U Airlines Co. Ltd.",
    "YM": "Montenegro Airlines",
    "YN": "Air Creebec (1994), Inc.",
    "YO": "Heli Air Monaco",
    "YP": "Air Premia Inc.",
    "YQ": "Helikopterservice AB, Euro Air",
    "YR": "Scenic Airlines, Inc.",
    "YS": "Flightlink Limited",
    "YT": "Air Togo S.A.",
    "YU": "EuroAtlantic Airways, S.A.",
    "YV": "Mesa Airlines, Inc.",
    "YW": "Air Nostrum L.A.M.S.A.",
    "YX": "Midwest Express Airlines, Inc.",
    "YY": "Lufthansa Cargo AG",
    "YZ": "Flywell Airlines Private Limited t/a Zimbabwe Airlink",
    "Z0": "Norse Atlantic UK Limited",
    "Z1": "Airline Control Systems (Pty) Ltd",
    "Z2": "Zest Airways Inc.",
    "Z3": "Avient Aviation (Pty) Limited",
    "Z4": "Zagrosjet Airlines",
    "Z5": "Global Africa Cargo",
    "Z7": "Zimbabwe Express Airlines",
    "Z8": "Pulkovo Aviation Enterprise",
    "Z9": "Aero Zambia",
    "ZA": "Access Air, Inc.",
    "ZB": "Monarch Airlines Ltd.",
    "ZC": "Flyafrica Zimbabwe (PVT) Limited",
    "ZD": "EWA Air",
    "ZE": "Lineas Aereas Azteca, S.A. de C.V.",
    "ZF": "Airborne of Sweden AB",
    "ZG": "Joint Stock Company Airline 'Groznyy Avia'",
    "ZH": "Air Truck Lineas Aereas, SA",
    "ZI": "Aigle Azur",
    "ZJ": "Air Routing International L.P.",
    "ZK": "Great Lakes Aviation Ltd.",
    "ZL": "Regional Express Pty Limited",
    "ZM": "Scibe-Airlift",
    "ZN": "Zambia Airways (2014) Limited",
    "ZO": "Central Air Transpsort Services",
    "ZP": "Air St. Thomas",
    "ZQ": "Caribbean Sun Airlines, Inc",
    "ZR": "Casair Aviation Services Ltd.",
    "ZS": "Solinair Latelsko Podjetjet d.o.o.",
    "ZT": "Air Zambezi",
    "ZU": "Air Bashkortostan Ltd",
    "ZV": "V Air Corporation",
    "ZW": "Air Wisconsin Airlines Corporation (AWAC)",
    "ZX": "Zoom Airlines Ltd",
    "ZY": "Sik-Ay Hava Tasimacilik A.S.",
}
